In [1]:
import numpy as np

In [2]:
W = np.random.randn(10, 3) 
print(W)

[[ 0.79313208 -1.24339351  1.43673548]
 [ 0.78180919  1.30526047  0.21841507]
 [-0.70750455 -0.64565228  0.2164616 ]
 [ 1.17473485  0.67588791  0.4162247 ]
 [-0.32332364 -1.24305439 -1.28615975]
 [-0.94792133 -1.00650621 -0.3957956 ]
 [ 1.55084476 -0.37132429 -0.20527103]
 [-0.11054159  3.37728274 -0.01538769]
 [-0.17072814  1.66416001 -1.46109923]
 [-0.21436663  0.71264835 -1.04172265]]


In [3]:
W.sum()

2.9338447151990441

In [4]:
id(W)

2178798573248

In [5]:
id(W.T)

2178798666016

In [6]:
a = np.arange(6).reshape(2,3)

In [7]:
a.T

array([[0, 3],
       [1, 4],
       [2, 5]])

In [8]:
print(id(a), id(a.T))

2178798666496 2178798667296


In [9]:
a.T[0] = 6
print(a)

[[6 1 2]
 [6 4 5]]


In [10]:
a = np.arange(6).reshape(2,-1)
a

array([[0, 1, 2],
       [3, 4, 5]])

In [11]:
for x in np.nditer(a, flags=['external_loop']):
    print (x)

[0 1 2 3 4 5]


In [12]:
for x in np.nditer(a, flags=['external_loop'], order='F'):
    print (x)

[0 3]
[1 4]
[2 5]


In [13]:
it = np.nditer(a, flags=['multi_index'])
while not it.finished:
    print ("%d <%s>" % (it[0], it.multi_index), end='\n')
    it.iternext()

0 <(0, 0)>
1 <(0, 1)>
2 <(0, 2)>
3 <(1, 0)>
4 <(1, 1)>
5 <(1, 2)>


In [14]:
a = np.arange(24).reshape(2,3,4)
print(a)


[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [15]:
for x in np.nditer(a, flags=['external_loop'], op_flags=['readonly'], order='F'):
    print(x)

[ 0 12]
[ 4 16]
[ 8 20]
[ 1 13]
[ 5 17]
[ 9 21]
[ 2 14]
[ 6 18]
[10 22]
[ 3 15]
[ 7 19]
[11 23]


In [16]:
a.ndim

3

In [17]:
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [18]:
a.mean(axis=0)

array([[  6.,   7.,   8.,   9.],
       [ 10.,  11.,  12.,  13.],
       [ 14.,  15.,  16.,  17.]])

In [19]:
a.mean(axis=-1)

array([[  1.5,   5.5,   9.5],
       [ 13.5,  17.5,  21.5]])

In [20]:
from random import randrange
tuple([randrange(m) for m in [50,50]])

(21, 3)

In [21]:
b = np.random.randn(4,4)

print(b)
print(np.maximum(0, b))

[[ 1.50957895  0.3187906  -0.75053018  0.15716627]
 [-0.24039372  0.78820454 -0.78411424 -0.8000272 ]
 [ 2.2448697  -0.21194539  0.7058942   0.01027608]
 [ 0.49601071  1.06373403 -1.10303681 -0.7464968 ]]
[[ 1.50957895  0.3187906   0.          0.15716627]
 [ 0.          0.78820454  0.          0.        ]
 [ 2.2448697   0.          0.7058942   0.01027608]
 [ 0.49601071  1.06373403  0.          0.        ]]


In [22]:
c = np.arange(24).reshape(4,6)
c

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [23]:
c[[1,3],[4,2]]

array([10, 20])

In [24]:
c[(1,3),(4,2)]

array([10, 20])

In [25]:
c[np.arange(3),(4,2,0)] = 0
c

array([[ 0,  1,  2,  3,  0,  5],
       [ 6,  7,  0,  9, 10, 11],
       [ 0, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [26]:
np.ones([3,4])

array([[ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.]])

In [27]:
np.array([1,9.-2,-5.7,0]) > 0


array([ True,  True, False, False], dtype=bool)

In [28]:
m =np.array([1,9.-2,-5.7,0])
m

array([ 1. ,  7. , -5.7,  0. ])

In [29]:
a = np.arange(3*4*5).reshape(3,4,5)
a

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39]],

       [[40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59]]])

In [30]:
a[[0,2]]

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59]]])

In [31]:
b = np.arange(3*5).reshape(3,5)
b

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [32]:
np.array([0,1,2])*b.T

array([[ 0,  5, 20],
       [ 0,  6, 22],
       [ 0,  7, 24],
       [ 0,  8, 26],
       [ 0,  9, 28]])

In [33]:
b[:, [3,0]] = [0,1]
b

array([[ 1,  1,  2,  0,  4],
       [ 1,  6,  7,  0,  9],
       [ 1, 11, 12,  0, 14]])

In [34]:
np.arange(4).reshape(:,1)

SyntaxError: invalid syntax (<ipython-input-34-734e346ef497>, line 1)

In [35]:
c = np.arange(12).reshape(3,4)
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [36]:
c.sum(axis=0)

array([12, 15, 18, 21])

In [37]:
c.sum(axis=-1).reshape(-1, 1)

array([[ 6],
       [22],
       [38]])

In [38]:
d = np.array([1.1, 2.2, 3.3])

In [39]:
e = np.array([1.1, 2.2, 3.3])
(d == e).all()

True

In [40]:
b1 = np.array([True, False])
print(b1)
b2 = np.array([1, 0])
b2

[ True False]


array([1, 0])

In [41]:
b1 == b2

array([ True,  True], dtype=bool)

In [42]:
b1

array([ True, False], dtype=bool)

In [43]:
b2

array([1, 0])

In [69]:
b[[0,2],:]

array([[ 1,  1,  2,  0,  4],
       [ 1, 11, 12,  0, 14]])

In [71]:
np.array([10]).shape


(1,)

In [74]:
np.empty(1).shape

(1,)