In [7]:
import numpy as np

In [2]:
W = np.random.randn(10, 3) 
print(W)

[[ 0.79313208 -1.24339351  1.43673548]
 [ 0.78180919  1.30526047  0.21841507]
 [-0.70750455 -0.64565228  0.2164616 ]
 [ 1.17473485  0.67588791  0.4162247 ]
 [-0.32332364 -1.24305439 -1.28615975]
 [-0.94792133 -1.00650621 -0.3957956 ]
 [ 1.55084476 -0.37132429 -0.20527103]
 [-0.11054159  3.37728274 -0.01538769]
 [-0.17072814  1.66416001 -1.46109923]
 [-0.21436663  0.71264835 -1.04172265]]


In [4]:
results = {}
for i in range(5):
    results[(i,i+1)] = list((i+2, i+3))
results

{(0, 1): [2, 3],
 (1, 2): [3, 4],
 (2, 3): [4, 5],
 (3, 4): [5, 6],
 (4, 5): [6, 7]}

In [5]:
[x for x in results]

[(0, 1), (1, 2), (2, 3), (3, 4), (4, 5)]

In [8]:
a = np.arange(15).reshape(3,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [9]:
a[:-1,:]

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [10]:
a.T


array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [11]:
b = np.arange(120).reshape(2,3,4,5)
b

array([[[[  0,   1,   2,   3,   4],
         [  5,   6,   7,   8,   9],
         [ 10,  11,  12,  13,  14],
         [ 15,  16,  17,  18,  19]],

        [[ 20,  21,  22,  23,  24],
         [ 25,  26,  27,  28,  29],
         [ 30,  31,  32,  33,  34],
         [ 35,  36,  37,  38,  39]],

        [[ 40,  41,  42,  43,  44],
         [ 45,  46,  47,  48,  49],
         [ 50,  51,  52,  53,  54],
         [ 55,  56,  57,  58,  59]]],


       [[[ 60,  61,  62,  63,  64],
         [ 65,  66,  67,  68,  69],
         [ 70,  71,  72,  73,  74],
         [ 75,  76,  77,  78,  79]],

        [[ 80,  81,  82,  83,  84],
         [ 85,  86,  87,  88,  89],
         [ 90,  91,  92,  93,  94],
         [ 95,  96,  97,  98,  99]],

        [[100, 101, 102, 103, 104],
         [105, 106, 107, 108, 109],
         [110, 111, 112, 113, 114],
         [115, 116, 117, 118, 119]]]])

In [12]:
b.T.shape

(5, 4, 3, 2)

In [13]:
b.T

array([[[[  0,  60],
         [ 20,  80],
         [ 40, 100]],

        [[  5,  65],
         [ 25,  85],
         [ 45, 105]],

        [[ 10,  70],
         [ 30,  90],
         [ 50, 110]],

        [[ 15,  75],
         [ 35,  95],
         [ 55, 115]]],


       [[[  1,  61],
         [ 21,  81],
         [ 41, 101]],

        [[  6,  66],
         [ 26,  86],
         [ 46, 106]],

        [[ 11,  71],
         [ 31,  91],
         [ 51, 111]],

        [[ 16,  76],
         [ 36,  96],
         [ 56, 116]]],


       [[[  2,  62],
         [ 22,  82],
         [ 42, 102]],

        [[  7,  67],
         [ 27,  87],
         [ 47, 107]],

        [[ 12,  72],
         [ 32,  92],
         [ 52, 112]],

        [[ 17,  77],
         [ 37,  97],
         [ 57, 117]]],


       [[[  3,  63],
         [ 23,  83],
         [ 43, 103]],

        [[  8,  68],
         [ 28,  88],
         [ 48, 108]],

        [[ 13,  73],
         [ 33,  93],
         [ 53, 113]],

        [[ 18,  78]