In [2]:
import numpy as np

In [3]:
W = np.random.randn(10, 3) 
print(W)

[[ 0.38283176 -1.09500407  0.14099611]
 [ 0.13585966  1.39120301 -0.11666991]
 [ 0.4572811  -0.16353031 -0.0415634 ]
 [-0.53566005  0.63295391  0.63992781]
 [-0.86205406 -1.03252252  1.912214  ]
 [-0.41886838 -0.58887703  1.4171121 ]
 [ 1.16264108 -2.40207949 -0.82375116]
 [-1.13517713  0.77343122 -0.02080932]
 [-1.81158896 -0.31176531  0.6771615 ]
 [-0.28064031  1.47781927 -1.37112727]]


In [4]:
W.sum()

-1.8102561308255927

In [5]:
id(W)

2683552511920

In [6]:
id(W.T)

2683552600432

In [7]:
a = np.arange(6).reshape(2,3)

In [8]:
a.T

array([[0, 3],
       [1, 4],
       [2, 5]])

In [9]:
print(id(a), id(a.T))

2683552601632 2683552601712


In [10]:
a.T[0] = 6
print(a)

[[6 1 2]
 [6 4 5]]


In [11]:
a = np.arange(6).reshape(2,-1)
a

array([[0, 1, 2],
       [3, 4, 5]])

In [12]:
for x in np.nditer(a, flags=['external_loop']):
    print (x)

[0 1 2 3 4 5]


In [13]:
for x in np.nditer(a, flags=['external_loop'], order='F'):
    print (x)

[0 3]
[1 4]
[2 5]


In [14]:
it = np.nditer(a, flags=['multi_index'])
while not it.finished:
    print ("%d <%s>" % (it[0], it.multi_index), end='\n')
    it.iternext()

0 <(0, 0)>
1 <(0, 1)>
2 <(0, 2)>
3 <(1, 0)>
4 <(1, 1)>
5 <(1, 2)>


In [15]:
a = np.arange(24).reshape(2,3,4)
print(a)


[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [16]:
for x in np.nditer(a, flags=['external_loop'], op_flags=['readonly'], order='F'):
    print(x)

[ 0 12]
[ 4 16]
[ 8 20]
[ 1 13]
[ 5 17]
[ 9 21]
[ 2 14]
[ 6 18]
[10 22]
[ 3 15]
[ 7 19]
[11 23]


In [17]:
a.ndim

3

In [18]:
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [19]:
a.mean(axis=0)

array([[  6.,   7.,   8.,   9.],
       [ 10.,  11.,  12.,  13.],
       [ 14.,  15.,  16.,  17.]])

In [20]:
a.mean(axis=-1)

array([[  1.5,   5.5,   9.5],
       [ 13.5,  17.5,  21.5]])

In [21]:
from random import randrange
tuple([randrange(m) for m in [50,50]])

(42, 14)

In [22]:
b = np.random.randn(4,4)

print(b)
print(np.maximum(0, b))

[[-0.9995967   0.71801639 -0.96314264 -0.42486499]
 [ 0.70440644 -1.07326701  0.64324363 -0.49984025]
 [ 1.013818   -1.69580135 -1.50510939 -1.67329159]
 [-0.11051104  0.06151048  1.42421131  1.07109955]]
[[ 0.          0.71801639  0.          0.        ]
 [ 0.70440644  0.          0.64324363  0.        ]
 [ 1.013818    0.          0.          0.        ]
 [ 0.          0.06151048  1.42421131  1.07109955]]


In [23]:
c = np.arange(24).reshape(4,6)
c

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [24]:
c[[1,3],[4,2]]

array([10, 20])

In [25]:
c[(1,3),(4,2)]

array([10, 20])

In [26]:
c[np.arange(3),(4,2,0)] = 0
c

array([[ 0,  1,  2,  3,  0,  5],
       [ 6,  7,  0,  9, 10, 11],
       [ 0, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [27]:
np.ones([3,4])

array([[ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.]])

In [28]:
np.array([1,9.-2,-5.7,0]) > 0


array([ True,  True, False, False], dtype=bool)

In [31]:
m =np.array([1,9.-2,-5.7,0])
m

array([ 1. ,  7. , -5.7,  0. ])

In [37]:
a = np.arange(3*4*5).reshape(3,4,5)
a

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39]],

       [[40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59]]])

In [40]:
a[[0,2]]

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59]]])

In [41]:
b = np.arange(3*5).reshape(3,5)
b

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [45]:
np.array([0,1,2])*b.T

array([[ 0,  5, 20],
       [ 0,  6, 22],
       [ 0,  7, 24],
       [ 0,  8, 26],
       [ 0,  9, 28]])

In [49]:
b[:, [3,0]] = [0,1]
b

array([[ 1,  1,  2,  0,  4],
       [ 1,  6,  7,  0,  9],
       [ 1, 11, 12,  0, 14]])

In [61]:
np.arange(4).reshape(:,1)

SyntaxError: invalid syntax (<ipython-input-61-734e346ef497>, line 1)

In [68]:
c = np.arange(12).reshape(3,4)
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [69]:
c.sum(axis=0)

array([12, 15, 18, 21])

In [74]:
c.sum(axis=-1).reshape(-1, 1)

array([[ 6],
       [22],
       [38]])

In [85]:
d = np.array([1.1, 2.2, 3.3])

In [86]:
e = np.array([1.1, 2.2, 3.3])
(d == e).all()

True

In [89]:
b1 = np.array([True, False])
print(b1)
b2 = np.array([1, 0])
b2

[ True False]


array([1, 0])

In [90]:
b1 == b2

array([ True,  True], dtype=bool)

In [91]:
b1

array([ True, False], dtype=bool)

In [92]:
b2

array([1, 0])